# Generated by Django 6.0.6 on 2026-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ('-created_at',), 'verbose_name': 'news article', 'verbose_name_plural': 'news articles'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
