# Generated by Django 6.0.7 on 2026-07-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'about content', 'verbose_name_plural': 'about contents'},
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
