# Generated by Django 6.0.6 on 2026-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutcontent_options_aboutcontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='title',
            field=models.CharField(default='About Us', max_length=255),
        ),
    ]
