# Generated by Django 6.0.6 on 2026-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_dish_in_category'),
        ),
    ]
