# Generated by Django 6.0.6 on 2026-07-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_unique_dish_in_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'name'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('order', 'name'), 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
    ]
