# Generated by Django 6.0.6 on 2026-07-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_translations_dish_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
